/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import interfaces.ISeating;
import java.awt.Point;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patr0805
 */
public class FlightBrowser extends javax.swing.JFrame {
    DatabaseHandler database;
    final Flight[] flights;
    /**
     * Creates new form FlightBrowser
     */
    public FlightBrowser(DatabaseHandler database) {
        initComponents();
        this.database = database;
       flights = database.getFlights();
      UpdateTable();
    }
    void UpdateTable()
    {
        flightTable.removeAll();
         for (Flight flight : flights)
       {
           if (!(flight.getID().contains(searchFlightIDTextField.getText()) || flight.getOrigin().contains((String) searchOriginComboBox.getSelectedItem()) || flight.getDestination().contains((String) searchDestinationComboBox.getSelectedItem()) || flight.getDepartureTime().toString().contains(searchDepartureTextField.getText()) || flight.getArrivalTime().toString().contains(searchArrivalTextField.getText())))
               continue;
           
          //Get number of avavlible seats
          ISeating seating = flight.getSeating();
          Iterator<Point> seats = seating.getSeatIterator();
          int numberOfFreeSeats = 0;
          while (seats.hasNext())
          {
              if (!seating.getSeatStatus((Point) seats))
              {
                  numberOfFreeSeats++;
              }
              seats.next();
          }
          if (numberOfFreeSeats > Integer.parseInt(searchMinSeatsTextField.getText()))
          {
              continue;
          }
          DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
          model.addRow(new Object[]{flight.id,flight.getOrigin(),flight.getDestination(),flight.getDepartureTime(),flight.getArrivalTime(),numberOfFreeSeats});
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchFlightIDTextField = new javax.swing.JTextField();
        searchFlightIDLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        searchOriginLabel = new javax.swing.JLabel();
        searchOriginComboBox = new javax.swing.JComboBox();
        searchDestinationLabel = new javax.swing.JLabel();
        searchDestinationComboBox = new javax.swing.JComboBox();
        searchDepartureTextField = new javax.swing.JTextField();
        searchDepartureDLabel = new javax.swing.JLabel();
        searchArrivalLabel = new javax.swing.JLabel();
        searchArrivalTextField = new javax.swing.JTextField();
        searchMinSeatsLabel = new javax.swing.JLabel();
        searchMinSeatsTextField = new javax.swing.JTextField();
        clearSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        backToMenuButton = new javax.swing.JButton();
        showReservationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("flightFrame"); // NOI18N

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleLabel.setText("Flights");
        titleLabel.setName("titleLabel"); // NOI18N

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        searchPanel.setToolTipText("");

        searchFlightIDTextField.setText("jTextField1");

        searchFlightIDLabel.setText("FlightID");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchOriginLabel.setText("Origin");

        searchOriginComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchDestinationLabel.setText("Destination");

        searchDestinationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchDepartureTextField.setText("jTextField1");

        searchDepartureDLabel.setText("Departure");

        searchArrivalLabel.setText("Arrival");

        searchArrivalTextField.setText("jTextField1");

        searchMinSeatsLabel.setText("Minimum number of free seats");

        searchMinSeatsTextField.setText("jTextField1");

        clearSearchButton.setText("Clear");
        clearSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchFlightIDLabel)
                        .addGap(25, 25, 25)
                        .addComponent(searchFlightIDTextField))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchOriginLabel)
                        .addGap(34, 34, 34)
                        .addComponent(searchOriginComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchDestinationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchDepartureDLabel)
                        .addGap(5, 5, 5)
                        .addComponent(searchDepartureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchArrivalLabel)
                        .addGap(25, 25, 25)
                        .addComponent(searchArrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchMinSeatsLabel)
                        .addGap(8, 8, 8)
                        .addComponent(searchMinSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearSearchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchFlightIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchDepartureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchFlightIDLabel)
                                    .addComponent(searchDepartureDLabel))))
                        .addGap(7, 7, 7)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchOriginLabel))
                            .addComponent(searchOriginComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchArrivalLabel))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(searchArrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchDestinationLabel))
                            .addComponent(searchDestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchMinSeatsLabel))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(searchMinSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap())
        );

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FlightID", "Origin", "Destination", "Departure", "Arrival", "Free seats"
            }
        ));
        flightTable.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(flightTable);

        backToMenuButton.setText("Back to mainmenu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        showReservationButton.setText("Show reservations for selection");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backToMenuButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showReservationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showReservationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backToMenuButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        // TODO add your handling code here:
      dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
      UpdateTable();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchButtonActionPerformed
        // TODO add your handling code here:
        searchFlightIDTextField.setText("");
        searchOriginComboBox.setSelectedIndex(-1);
        searchDestinationComboBox.setSelectedIndex(-1);
        searchDepartureTextField.setText("");
        searchArrivalTextField.setText("");
        searchMinSeatsTextField.setText("");
    }//GEN-LAST:event_clearSearchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JButton clearSearchButton;
    private javax.swing.JTable flightTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel searchArrivalLabel;
    private javax.swing.JTextField searchArrivalTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchDepartureDLabel;
    private javax.swing.JTextField searchDepartureTextField;
    private javax.swing.JComboBox searchDestinationComboBox;
    private javax.swing.JLabel searchDestinationLabel;
    private javax.swing.JLabel searchFlightIDLabel;
    private javax.swing.JTextField searchFlightIDTextField;
    private javax.swing.JLabel searchMinSeatsLabel;
    private javax.swing.JTextField searchMinSeatsTextField;
    private javax.swing.JComboBox searchOriginComboBox;
    private javax.swing.JLabel searchOriginLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton showReservationButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
